[Interface]
PrivateKey = <chiave-privata-windows1-generata-dal-container>
Address = 10.8.0.6/32
DNS = 10.8.0.5

[Peer]
PublicKey = <publickey-server-generata-dal-container>
Endpoint = sseapid.isti.cnr.it:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
