port 1194
proto udp
dev tun
topology subnet

user nobody
group nogroup
persist-key
persist-tun

ca /etc/openvpn/server/pki/ca.crt
cert /etc/openvpn/server/pki/issued/server.crt
key /etc/openvpn/server/pki/private/server.key
dh none
ecdh-curve prime256v1
tls-crypt /etc/openvpn/server/pki/ta.key

server 192.168.4.0 255.255.255.0 nopool
ifconfig-pool 192.168.4.150 192.168.4.254 255.255.255.0
ifconfig-pool-persist /var/log/openvpn/ipp.txt
client-config-dir /etc/openvpn/server/ccd

push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 192.168.4.146"

keepalive 10 120
explicit-exit-notify 1

tls-version-min 1.2
remote-cert-tls client
verify-client-cert require
auth SHA256
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
data-ciphers-fallback AES-256-CBC

status /var/log/openvpn/status.log
verb 3
