[Interface]
PrivateKey = <chiave-privata-macos1-generata-dal-container>
Address = 192.168.4.153/32
DNS = 192.168.4.146

[Peer]
PublicKey = <publickey-server-generata-dal-container>
Endpoint = sseapid.isti.cnr.it:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
