[Interface]
Address = 10.8.0.5
PrivateKey = gG78qJBTAtprQu8Ybnp07hn3UOwIBS0bbdVrcFAQxkg=
ListenPort = 51820
DNS = 10.8.0.5

[Peer]
PublicKey = PJdnM+/AA0t6QAh86eT1f7Etbb5KIRqPOyezMdTzKSc=
PresharedKey = YaqLgXGz41JUEzUANDm+HN6cwVi1RQGPSwzVAJ1RWsA=
Endpoint = sseapid.isti.cnr.it:51820
AllowedIPs = 0.0.0.0/0,::/0