[Interface]
PrivateKey = <generata-dal-container-nel-peer>
Address = 192.168.4.150/32
DNS = 192.168.4.146

[Peer]
PublicKey = <publickey-server-generata-dal-container>
Endpoint = sseapid.isti.cnr.it:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
