[Interface]
Address = 192.168.4.1/24
ListenPort = 51820
PrivateKey = <generata-dal-container-in-wireguard/config/server/privatekey>

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# dns1
PublicKey = <generata-dal-container-in-wireguard/config/peer_dns1/publickey>
AllowedIPs = 192.168.4.146/32

[Peer]
# android1
PublicKey = <generata-dal-container-in-wireguard/config/peer_android1/publickey>
AllowedIPs = 192.168.4.150/32

[Peer]
# android2
PublicKey = <generata-dal-container-in-wireguard/config/peer_android2/publickey>
AllowedIPs = 192.168.4.151/32

[Peer]
# android3
PublicKey = <generata-dal-container-in-wireguard/config/peer_android3/publickey>
AllowedIPs = 192.168.4.152/32

[Peer]
# macos1
PublicKey = <generata-dal-container-in-wireguard/config/peer_macos1/publickey>
AllowedIPs = 192.168.4.153/32

[Peer]
# windows1
PublicKey = <generata-dal-container-in-wireguard/config/peer_windows1/publickey>
AllowedIPs = 192.168.4.154/32

[Peer]
# linux1
PublicKey = <generata-dal-container-in-wireguard/config/peer_linux1/publickey>
AllowedIPs = 192.168.4.155/32
