[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = <generata-dal-container-in-wireguard/config/server/privatekey>

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# android1
PublicKey = <generata-dal-container-in-wireguard/config/peer_android1/publickey>
AllowedIPs = 10.8.0.2/32

[Peer]
# android2
PublicKey = <generata-dal-container-in-wireguard/config/peer_android2/publickey>
AllowedIPs = 10.8.0.3/32

[Peer]
# android3
PublicKey = <generata-dal-container-in-wireguard/config/peer_android3/publickey>
AllowedIPs = 10.8.0.4/32

